services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  node_modules1:
    image: node:16
    container_name: node_modules1
    working_dir: /var/www/html
    volumes:
      - ./site1/TP-Final-3IW-ESGI:/var/www/html
      - node_modules_site1:/var/www/html/node_modules
    command: sh -c "npm install && tail -f /dev/null"

  node_modules2:
    image: node:16
    container_name: node_modules2
    working_dir: /var/www/html
    volumes:
      - ./site2/TP-Final-3IW-ESGI:/var/www/html
      - node_modules_site2:/var/www/html/node_modules
    command: sh -c "npm install && tail -f /dev/null"

  vendor1:
    image: composer:latest
    container_name: vendor1
    working_dir: /var/www/html
    volumes:
      - ./site1/TP-Final-3IW-ESGI:/var/www/html
      - vendor_site1:/var/www/html/vendor
    command: sh -c "composer update && composer install && tail -f /dev/null"

  vendor2:
    image: composer:latest
    container_name: vendor2
    working_dir: /var/www/html
    volumes:
      - ./site2/TP-Final-3IW-ESGI:/var/www/html
      - vendor_site2:/var/www/html/vendor
    command: sh -c "composer update && composer install && tail -f /dev/null"

  php1:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile
    container_name: php1
    volumes:
      - ./site1/TP-Final-3IW-ESGI:/var/www/html
      - vendor_site1:/var/www/html/vendor
      - node_modules_site1:/var/www/html/node_modules
    working_dir: /var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql
      - vendor1
      - node_modules1
    command: php-fpm

  php2:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile
    container_name: php2
    volumes:
      - ./site2/TP-Final-3IW-ESGI:/var/www/html
      - vendor_site2:/var/www/html/vendor
      - node_modules_site2:/var/www/html/node_modules
    working_dir: /var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql
      - vendor2
      - node_modules2
    command: php-fpm

  nginx1:
    image: nginx:latest
    container_name: nginx1
    ports:
      - '8081:80'
    volumes:
      - ./site1/TP-Final-3IW-ESGI:/var/www/html
      - ./confs/nginx1.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php1

  nginx2:
    image: nginx:latest
    container_name: nginx2
    ports:
      - '8082:80'
    volumes:
      - ./site2/TP-Final-3IW-ESGI:/var/www/html
      - ./confs/nginx2.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2

volumes:
  db_data:
  vendor_site1:
  vendor_site2:
  node_modules_site1:
  node_modules_site2: